### ISSUE TITLE
I've added support for your output format to my chapter projects

### ISSUE THREAD

**Issue by Mtillmann** [slhck/scenecut-extractor#4]
Hi, just wanted to inform you that I've added your format to my [chaptertool](https://github.com/Mtillmann/chaptertool) and [chapters](https://github.com/Mtillmann/chapters) projects. You've build a great tool and combined with my chaptertool, even better workflows are possible! Thanks

**Comment by slhck** [comment]
Great, thanks for letting me know! Hadn't heard about `chaptertool` before, but it looks really useful. I added it to the README as a related project.
